name: triple_lang_builder
description: A translation builder which generates automatically .arb-files in English, German and Spanish with help of the DeepL-API.
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  yaml: ^3.1.0
  yaml_writer: ^1.0.3

dev_dependencies:
  test: ^1.16.0
